export const FETCH_RESULTS = "FETCH_RESULTS";
export const FETCH_PAPERS = "FETCH_PAPERS";
export const FETCH_PATENTS = "FETCH_PATENTS";
export const SET_LOADING = "SET_LOADING";
export const CLEAR_RESULTS = "CLEAR_RESULTS";
export const SAVE_PAPERS = "SAVE_PAPERS";
export const SAVE_PATENTS = "SAVE_PATENTS";