export const FETCH_RESULTS = "FETCH_RESULTS";
export const FETCH_PAPERS = "FETCH_PAPERS";
export const FETCH_PATENTS = "FETCH_PATENTS";
export const SET_LOADING = "SET_LOADING";
export const CLEAR_RESULTS = "CLEAR_RESULTS";
export const SAVE_PAPERS = "SAVE_PAPERS";
export const SAVE_PATENTS = "SAVE_PATENTS";
export const APPEND_PAPERS = "APPEND_PAPERS";
export const APPEND_PATENTS = "APPEND_PATENTS";
export const LOADING_PAPERS = "LOADING_PAPERS";
export const LOADING_PATENTS = "LOADING_PATENTS";
export const SET_SELECTED_PAPERS = "SET_SELECTED_PAPERS";
export const CLEAR_SELECTED_PAPERS = "CLEAR_SELECTED_PAPERS";
export const SET_SELECTED_PATENTS = "SET_SELECTED_PATENTS";
export const CLEAR_SELECTED_PATENTS = "CLEAR_SELECTED_PATENTS";

